# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Zihao/projects/cppbach

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Zihao/projects/cppbach

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Zihao/projects/cppbach/CMakeFiles /Users/Zihao/projects/cppbach/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Zihao/projects/cppbach/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppbach

# Build rule for target.
cppbach: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppbach
.PHONY : cppbach

# fast build rule for target.
cppbach/fast:
	$(MAKE) -f CMakeFiles/cppbach.dir/build.make CMakeFiles/cppbach.dir/build
.PHONY : cppbach/fast

#=============================================================================
# Target rules for targets named midifile

# Build rule for target.
midifile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midifile
.PHONY : midifile

# fast build rule for target.
midifile/fast:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/build
.PHONY : midifile/fast

#=============================================================================
# Target rules for targets named portmidi

# Build rule for target.
portmidi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 portmidi
.PHONY : portmidi

# fast build rule for target.
portmidi/fast:
	$(MAKE) -f CMakeFiles/portmidi.dir/build.make CMakeFiles/portmidi.dir/build
.PHONY : portmidi/fast

#=============================================================================
# Target rules for targets named rtmidi

# Build rule for target.
rtmidi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmidi
.PHONY : rtmidi

# fast build rule for target.
rtmidi/fast:
	$(MAKE) -f CMakeFiles/rtmidi.dir/build.make CMakeFiles/rtmidi.dir/build
.PHONY : rtmidi/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cppbach.dir/build.make CMakeFiles/cppbach.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cppbach.dir/build.make CMakeFiles/cppbach.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cppbach.dir/build.make CMakeFiles/cppbach.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... portmidi"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cppbach"
	@echo "... midifile"
	@echo "... rtmidi"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

